# NOTE: Deprecated, this config may not work with the latest version of the code
MODEL: 'RSCR'
ENCODER:
  TYPE: 'ResUNet'
  BLOCK_TYPE: 1
  NUM_BLOCKS: '3-3-3'
  NOT_CONCAT: False
  NUM_OUT_LAYERS: 32
AGGREGATOR:
  TYPE: 'CorrelationVolumeWarpingQKV'
  POSITION_ENCODER: True
  MAX_SCORE_CHANNEL: True
HEAD:
  TYPE: 'DirectDeepTranslationMLP'
POSE_SOLVER: 'PNP'
PNP:
  USE_RANSAC: False
  ALGO: 'SQPNP'
  RANSAC_ITER: 1000
  REPROJECTION_INLIER_THRESHOLD: 3
  CONFIDENCE: 0.9999
TRAINING:
  LR: 1e-4
  # loss
  ROT_LOSS: 'rot_angle_loss'
  TRANS_LOSS: 'trans_l1_loss'
  LAMBDA: 1.
  REPRO_LOSS: 
    TYPE: 'l1+sqrt'
    DEPTH_MIN: 0.1
    DEPTH_MAX: 1000
    DEPTH_TARGET: 5
    REPRO_HARD_CLAMP: 1000
    REPRO_SOFT_CLAMP: 50
    REPRO_SOFT_CLAMP_MIN: 1
BACKPROJECT_ANCHORS: False
